// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: user/users/user_message.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-gateway/pb/user/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role             string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	UniversityId     string                 `protobuf:"bytes,5,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName   string                 `protobuf:"bytes,6,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	ProgramStudiId   string                 `protobuf:"bytes,7,opt,name=program_studi_id,json=programStudiId,proto3" json:"program_studi_id,omitempty"`
	ProgramStudiName string                 `protobuf:"bytes,8,opt,name=program_studi_name,json=programStudiName,proto3" json:"program_studi_name,omitempty"`
	IsActive         bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	UpdatedBy        string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_users_user_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *User) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *User) GetProgramStudiId() string {
	if x != nil {
		return x.ProgramStudiId
	}
	return ""
}

func (x *User) GetProgramStudiName() string {
	if x != nil {
		return x.ProgramStudiName
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_user_users_user_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{1}
}

func (x *UserList) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UserListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListInput) Reset() {
	*x = UserListInput{}
	mi := &file_user_users_user_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListInput) ProtoMessage() {}

func (x *UserListInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListInput.ProtoReflect.Descriptor instead.
func (*UserListInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{2}
}

func (x *UserListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *UserListInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RegisterInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Role             string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	UniversityId     string                 `protobuf:"bytes,5,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName   string                 `protobuf:"bytes,6,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	ProgramStudiId   string                 `protobuf:"bytes,7,opt,name=program_studi_id,json=programStudiId,proto3" json:"program_studi_id,omitempty"`
	ProgramStudiName string                 `protobuf:"bytes,8,opt,name=program_studi_name,json=programStudiName,proto3" json:"program_studi_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterInput) Reset() {
	*x = RegisterInput{}
	mi := &file_user_users_user_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInput) ProtoMessage() {}

func (x *RegisterInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInput.ProtoReflect.Descriptor instead.
func (*RegisterInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterInput) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *RegisterInput) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *RegisterInput) GetProgramStudiId() string {
	if x != nil {
		return x.ProgramStudiId
	}
	return ""
}

func (x *RegisterInput) GetProgramStudiName() string {
	if x != nil {
		return x.ProgramStudiName
	}
	return ""
}

type LoginInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInput) Reset() {
	*x = LoginInput{}
	mi := &file_user_users_user_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInput) ProtoMessage() {}

func (x *LoginInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInput.ProtoReflect.Descriptor instead.
func (*LoginInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{4}
}

func (x *LoginInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_users_user_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{5}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type UpdateUserInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role             string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	UniversityId     string                 `protobuf:"bytes,4,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	UniversityName   string                 `protobuf:"bytes,5,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	ProgramStudiId   string                 `protobuf:"bytes,6,opt,name=program_studi_id,json=programStudiId,proto3" json:"program_studi_id,omitempty"`
	ProgramStudiName string                 `protobuf:"bytes,7,opt,name=program_studi_name,json=programStudiName,proto3" json:"program_studi_name,omitempty"`
	IsActive         bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateUserInput) Reset() {
	*x = UpdateUserInput{}
	mi := &file_user_users_user_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserInput) ProtoMessage() {}

func (x *UpdateUserInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserInput.ProtoReflect.Descriptor instead.
func (*UpdateUserInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UpdateUserInput) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *UpdateUserInput) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *UpdateUserInput) GetProgramStudiId() string {
	if x != nil {
		return x.ProgramStudiId
	}
	return ""
}

func (x *UpdateUserInput) GetProgramStudiName() string {
	if x != nil {
		return x.ProgramStudiName
	}
	return ""
}

func (x *UpdateUserInput) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ChangePasswordInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordInput) Reset() {
	*x = ChangePasswordInput{}
	mi := &file_user_users_user_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordInput) ProtoMessage() {}

func (x *ChangePasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordInput.ProtoReflect.Descriptor instead.
func (*ChangePasswordInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{7}
}

func (x *ChangePasswordInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangePasswordInput) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordInput) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ValidateTokenInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenInput) Reset() {
	*x = ValidateTokenInput{}
	mi := &file_user_users_user_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenInput) ProtoMessage() {}

func (x *ValidateTokenInput) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenInput.ProtoReflect.Descriptor instead.
func (*ValidateTokenInput) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateTokenInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_user_users_user_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_users_user_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_users_user_message_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_user_users_user_message_proto protoreflect.FileDescriptor

const file_user_users_user_message_proto_rawDesc = "" +
	"\n" +
	"\x1duser/users/user_message.proto\x12\x05users\x1a\"user/generic/generic_message.proto\"\xf4\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12#\n" +
	"\runiversity_id\x18\x05 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x06 \x01(\tR\x0euniversityName\x12(\n" +
	"\x10program_studi_id\x18\a \x01(\tR\x0eprogramStudiId\x12,\n" +
	"\x12program_studi_name\x18\b \x01(\tR\x10programStudiName\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"C\n" +
	"\bUserList\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.users.UserR\x05users\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"b\n" +
	"\rUserListInput\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.lms_user_services.PaginationR\n" +
	"pagination\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\x8f\x02\n" +
	"\rRegisterInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12#\n" +
	"\runiversity_id\x18\x05 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x06 \x01(\tR\x0euniversityName\x12(\n" +
	"\x10program_studi_id\x18\a \x01(\tR\x0eprogramStudiId\x12,\n" +
	"\x12program_studi_name\x18\b \x01(\tR\x10programStudiName\">\n" +
	"\n" +
	"LoginInput\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"e\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1f\n" +
	"\x04user\x18\x02 \x01(\v2\v.users.UserR\x04user\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\x8c\x02\n" +
	"\x0fUpdateUserInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12#\n" +
	"\runiversity_id\x18\x04 \x01(\tR\funiversityId\x12'\n" +
	"\x0funiversity_name\x18\x05 \x01(\tR\x0euniversityName\x12(\n" +
	"\x10program_studi_id\x18\x06 \x01(\tR\x0eprogramStudiId\x12,\n" +
	"\x12program_studi_name\x18\a \x01(\tR\x10programStudiName\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"k\n" +
	"\x13ChangePasswordInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"*\n" +
	"\x12ValidateTokenInput\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"N\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1f\n" +
	"\x04user\x18\x02 \x01(\v2\v.users.UserR\x04user2\xd0\x03\n" +
	"\vUserService\x12-\n" +
	"\bRegister\x12\x14.users.RegisterInput\x1a\v.users.User\x120\n" +
	"\x05Login\x12\x11.users.LoginInput\x1a\x14.users.LoginResponse\x12H\n" +
	"\rValidateToken\x12\x19.users.ValidateTokenInput\x1a\x1c.users.ValidateTokenResponse\x12-\n" +
	"\x04List\x12\x14.users.UserListInput\x1a\x0f.users.UserList\x12)\n" +
	"\x03Get\x12\x15.lms_user_services.Id\x1a\v.users.User\x12-\n" +
	"\x06Update\x12\x16.users.UpdateUserInput\x1a\v.users.User\x12L\n" +
	"\x0eChangePassword\x12\x1a.users.ChangePasswordInput\x1a\x1e.lms_user_services.BoolMessage\x12?\n" +
	"\x06Delete\x12\x15.lms_user_services.Id\x1a\x1e.lms_user_services.BoolMessageB!Z\x1flms-gateway/pb/user/users;usersb\x06proto3"

var (
	file_user_users_user_message_proto_rawDescOnce sync.Once
	file_user_users_user_message_proto_rawDescData []byte
)

func file_user_users_user_message_proto_rawDescGZIP() []byte {
	file_user_users_user_message_proto_rawDescOnce.Do(func() {
		file_user_users_user_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_users_user_message_proto_rawDesc), len(file_user_users_user_message_proto_rawDesc)))
	})
	return file_user_users_user_message_proto_rawDescData
}

var file_user_users_user_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_users_user_message_proto_goTypes = []any{
	(*User)(nil),                  // 0: users.User
	(*UserList)(nil),              // 1: users.UserList
	(*UserListInput)(nil),         // 2: users.UserListInput
	(*RegisterInput)(nil),         // 3: users.RegisterInput
	(*LoginInput)(nil),            // 4: users.LoginInput
	(*LoginResponse)(nil),         // 5: users.LoginResponse
	(*UpdateUserInput)(nil),       // 6: users.UpdateUserInput
	(*ChangePasswordInput)(nil),   // 7: users.ChangePasswordInput
	(*ValidateTokenInput)(nil),    // 8: users.ValidateTokenInput
	(*ValidateTokenResponse)(nil), // 9: users.ValidateTokenResponse
	(*generic.Pagination)(nil),    // 10: lms_user_services.Pagination
	(*generic.Id)(nil),            // 11: lms_user_services.Id
	(*generic.BoolMessage)(nil),   // 12: lms_user_services.BoolMessage
}
var file_user_users_user_message_proto_depIdxs = []int32{
	0,  // 0: users.UserList.users:type_name -> users.User
	10, // 1: users.UserListInput.pagination:type_name -> lms_user_services.Pagination
	0,  // 2: users.LoginResponse.user:type_name -> users.User
	0,  // 3: users.ValidateTokenResponse.user:type_name -> users.User
	3,  // 4: users.UserService.Register:input_type -> users.RegisterInput
	4,  // 5: users.UserService.Login:input_type -> users.LoginInput
	8,  // 6: users.UserService.ValidateToken:input_type -> users.ValidateTokenInput
	2,  // 7: users.UserService.List:input_type -> users.UserListInput
	11, // 8: users.UserService.Get:input_type -> lms_user_services.Id
	6,  // 9: users.UserService.Update:input_type -> users.UpdateUserInput
	7,  // 10: users.UserService.ChangePassword:input_type -> users.ChangePasswordInput
	11, // 11: users.UserService.Delete:input_type -> lms_user_services.Id
	0,  // 12: users.UserService.Register:output_type -> users.User
	5,  // 13: users.UserService.Login:output_type -> users.LoginResponse
	9,  // 14: users.UserService.ValidateToken:output_type -> users.ValidateTokenResponse
	1,  // 15: users.UserService.List:output_type -> users.UserList
	0,  // 16: users.UserService.Get:output_type -> users.User
	0,  // 17: users.UserService.Update:output_type -> users.User
	12, // 18: users.UserService.ChangePassword:output_type -> lms_user_services.BoolMessage
	12, // 19: users.UserService.Delete:output_type -> lms_user_services.BoolMessage
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_users_user_message_proto_init() }
func file_user_users_user_message_proto_init() {
	if File_user_users_user_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_users_user_message_proto_rawDesc), len(file_user_users_user_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_users_user_message_proto_goTypes,
		DependencyIndexes: file_user_users_user_message_proto_depIdxs,
		MessageInfos:      file_user_users_user_message_proto_msgTypes,
	}.Build()
	File_user_users_user_message_proto = out.File
	file_user_users_user_message_proto_goTypes = nil
	file_user_users_user_message_proto_depIdxs = nil
}
