// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: conference/conferences/conference_message.proto

package conferences

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-gateway/pb/conference/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Conference struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	StartTime      string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MeetingUrl     string                 `protobuf:"bytes,8,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conference) Reset() {
	*x = Conference{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conference) ProtoMessage() {}

func (x *Conference) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conference.ProtoReflect.Descriptor instead.
func (*Conference) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{0}
}

func (x *Conference) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conference) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Conference) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *Conference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Conference) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Conference) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Conference) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Conference) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

func (x *Conference) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Conference) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Conference) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Conference) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ConferenceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conferences   []*Conference          `protobuf:"bytes,1,rep,name=conferences,proto3" json:"conferences,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceList) Reset() {
	*x = ConferenceList{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceList) ProtoMessage() {}

func (x *ConferenceList) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceList.ProtoReflect.Descriptor instead.
func (*ConferenceList) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{1}
}

func (x *ConferenceList) GetConferences() []*Conference {
	if x != nil {
		return x.Conferences
	}
	return nil
}

func (x *ConferenceList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConferenceListInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pagination     *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConferenceListInput) Reset() {
	*x = ConferenceListInput{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceListInput) ProtoMessage() {}

func (x *ConferenceListInput) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceListInput.ProtoReflect.Descriptor instead.
func (*ConferenceListInput) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{2}
}

func (x *ConferenceListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ConferenceListInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

type ConferenceInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId string                 `protobuf:"bytes,1,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,2,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StartTime      string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	MeetingUrl     string                 `protobuf:"bytes,7,opt,name=meeting_url,json=meetingUrl,proto3" json:"meeting_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConferenceInput) Reset() {
	*x = ConferenceInput{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceInput) ProtoMessage() {}

func (x *ConferenceInput) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceInput.ProtoReflect.Descriptor instead.
func (*ConferenceInput) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{3}
}

func (x *ConferenceInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *ConferenceInput) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *ConferenceInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConferenceInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConferenceInput) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ConferenceInput) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *ConferenceInput) GetMeetingUrl() string {
	if x != nil {
		return x.MeetingUrl
	}
	return ""
}

type ConferenceParticipant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConferenceId  string                 `protobuf:"bytes,2,opt,name=conference_id,json=conferenceId,proto3" json:"conference_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,4,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	IsAttended    bool                   `protobuf:"varint,5,opt,name=is_attended,json=isAttended,proto3" json:"is_attended,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,6,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        string                 `protobuf:"bytes,7,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceParticipant) Reset() {
	*x = ConferenceParticipant{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceParticipant) ProtoMessage() {}

func (x *ConferenceParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceParticipant.ProtoReflect.Descriptor instead.
func (*ConferenceParticipant) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{4}
}

func (x *ConferenceParticipant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConferenceParticipant) GetConferenceId() string {
	if x != nil {
		return x.ConferenceId
	}
	return ""
}

func (x *ConferenceParticipant) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ConferenceParticipant) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *ConferenceParticipant) GetIsAttended() bool {
	if x != nil {
		return x.IsAttended
	}
	return false
}

func (x *ConferenceParticipant) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ConferenceParticipant) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

func (x *ConferenceParticipant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ConferenceParticipantList struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Participants  []*ConferenceParticipant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	Count         uint32                   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceParticipantList) Reset() {
	*x = ConferenceParticipantList{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceParticipantList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceParticipantList) ProtoMessage() {}

func (x *ConferenceParticipantList) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceParticipantList.ProtoReflect.Descriptor instead.
func (*ConferenceParticipantList) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{5}
}

func (x *ConferenceParticipantList) GetParticipants() []*ConferenceParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ConferenceParticipantList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ConferenceParticipantListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	ConferenceId  string                 `protobuf:"bytes,2,opt,name=conference_id,json=conferenceId,proto3" json:"conference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceParticipantListInput) Reset() {
	*x = ConferenceParticipantListInput{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceParticipantListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceParticipantListInput) ProtoMessage() {}

func (x *ConferenceParticipantListInput) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceParticipantListInput.ProtoReflect.Descriptor instead.
func (*ConferenceParticipantListInput) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{6}
}

func (x *ConferenceParticipantListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ConferenceParticipantListInput) GetConferenceId() string {
	if x != nil {
		return x.ConferenceId
	}
	return ""
}

type ConferenceParticipantInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConferenceId  string                 `protobuf:"bytes,1,opt,name=conference_id,json=conferenceId,proto3" json:"conference_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,3,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceParticipantInput) Reset() {
	*x = ConferenceParticipantInput{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceParticipantInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceParticipantInput) ProtoMessage() {}

func (x *ConferenceParticipantInput) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceParticipantInput.ProtoReflect.Descriptor instead.
func (*ConferenceParticipantInput) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{7}
}

func (x *ConferenceParticipantInput) GetConferenceId() string {
	if x != nil {
		return x.ConferenceId
	}
	return ""
}

func (x *ConferenceParticipantInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *ConferenceParticipantInput) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

type UpdateAttendanceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsAttended    bool                   `protobuf:"varint,2,opt,name=is_attended,json=isAttended,proto3" json:"is_attended,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,3,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        string                 `protobuf:"bytes,4,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAttendanceInput) Reset() {
	*x = UpdateAttendanceInput{}
	mi := &file_conference_conferences_conference_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAttendanceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAttendanceInput) ProtoMessage() {}

func (x *UpdateAttendanceInput) ProtoReflect() protoreflect.Message {
	mi := &file_conference_conferences_conference_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAttendanceInput.ProtoReflect.Descriptor instead.
func (*UpdateAttendanceInput) Descriptor() ([]byte, []int) {
	return file_conference_conferences_conference_message_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAttendanceInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAttendanceInput) GetIsAttended() bool {
	if x != nil {
		return x.IsAttended
	}
	return false
}

func (x *UpdateAttendanceInput) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *UpdateAttendanceInput) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

var File_conference_conferences_conference_message_proto protoreflect.FileDescriptor

const file_conference_conferences_conference_message_proto_rawDesc = "" +
	"\n" +
	"/conference/conferences/conference_message.proto\x12\vconferences\x1a(conference/generic/generic_message.proto\"\xf6\x02\n" +
	"\n" +
	"Conference\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x1f\n" +
	"\vmeeting_url\x18\b \x01(\tR\n" +
	"meetingUrl\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\"a\n" +
	"\x0eConferenceList\x129\n" +
	"\vconferences\x18\x01 \x03(\v2\x17.conferences.ConferenceR\vconferences\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x84\x01\n" +
	"\x13ConferenceListInput\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.lms_conference_services.PaginationR\n" +
	"pagination\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\"\xf6\x01\n" +
	"\x0fConferenceInput\x12(\n" +
	"\x10subject_class_id\x18\x01 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x02 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x1f\n" +
	"\vmeeting_url\x18\a \x01(\tR\n" +
	"meetingUrl\"\x84\x02\n" +
	"\x15ConferenceParticipant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rconference_id\x18\x02 \x01(\tR\fconferenceId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x04 \x01(\tR\vstudentName\x12\x1f\n" +
	"\vis_attended\x18\x05 \x01(\bR\n" +
	"isAttended\x12\x1b\n" +
	"\tjoined_at\x18\x06 \x01(\tR\bjoinedAt\x12\x17\n" +
	"\aleft_at\x18\a \x01(\tR\x06leftAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"y\n" +
	"\x19ConferenceParticipantList\x12F\n" +
	"\fparticipants\x18\x01 \x03(\v2\".conferences.ConferenceParticipantR\fparticipants\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"\x8a\x01\n" +
	"\x1eConferenceParticipantListInput\x12C\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2#.lms_conference_services.PaginationR\n" +
	"pagination\x12#\n" +
	"\rconference_id\x18\x02 \x01(\tR\fconferenceId\"\x83\x01\n" +
	"\x1aConferenceParticipantInput\x12#\n" +
	"\rconference_id\x18\x01 \x01(\tR\fconferenceId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x03 \x01(\tR\vstudentName\"~\n" +
	"\x15UpdateAttendanceInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vis_attended\x18\x02 \x01(\bR\n" +
	"isAttended\x12\x1b\n" +
	"\tjoined_at\x18\x03 \x01(\tR\bjoinedAt\x12\x17\n" +
	"\aleft_at\x18\x04 \x01(\tR\x06leftAt2\xe1\x02\n" +
	"\x11ConferenceService\x12E\n" +
	"\x04List\x12 .conferences.ConferenceListInput\x1a\x1b.conferences.ConferenceList\x12;\n" +
	"\x03Get\x12\x1b.lms_conference_services.Id\x1a\x17.conferences.Conference\x12?\n" +
	"\x06Create\x12\x1c.conferences.ConferenceInput\x1a\x17.conferences.Conference\x12:\n" +
	"\x06Update\x12\x17.conferences.Conference\x1a\x17.conferences.Conference\x12K\n" +
	"\x06Delete\x12\x1b.lms_conference_services.Id\x1a$.lms_conference_services.BoolMessage2\xfb\x02\n" +
	"\x1cConferenceParticipantService\x12[\n" +
	"\x04List\x12+.conferences.ConferenceParticipantListInput\x1a&.conferences.ConferenceParticipantList\x12U\n" +
	"\x06Create\x12'.conferences.ConferenceParticipantInput\x1a\".conferences.ConferenceParticipant\x12Z\n" +
	"\x10UpdateAttendance\x12\".conferences.UpdateAttendanceInput\x1a\".conferences.ConferenceParticipant\x12K\n" +
	"\x06Delete\x12\x1b.lms_conference_services.Id\x1a$.lms_conference_services.BoolMessageB3Z1lms-gateway/pb/conference/conferences;conferencesb\x06proto3"

var (
	file_conference_conferences_conference_message_proto_rawDescOnce sync.Once
	file_conference_conferences_conference_message_proto_rawDescData []byte
)

func file_conference_conferences_conference_message_proto_rawDescGZIP() []byte {
	file_conference_conferences_conference_message_proto_rawDescOnce.Do(func() {
		file_conference_conferences_conference_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conference_conferences_conference_message_proto_rawDesc), len(file_conference_conferences_conference_message_proto_rawDesc)))
	})
	return file_conference_conferences_conference_message_proto_rawDescData
}

var file_conference_conferences_conference_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conference_conferences_conference_message_proto_goTypes = []any{
	(*Conference)(nil),                     // 0: conferences.Conference
	(*ConferenceList)(nil),                 // 1: conferences.ConferenceList
	(*ConferenceListInput)(nil),            // 2: conferences.ConferenceListInput
	(*ConferenceInput)(nil),                // 3: conferences.ConferenceInput
	(*ConferenceParticipant)(nil),          // 4: conferences.ConferenceParticipant
	(*ConferenceParticipantList)(nil),      // 5: conferences.ConferenceParticipantList
	(*ConferenceParticipantListInput)(nil), // 6: conferences.ConferenceParticipantListInput
	(*ConferenceParticipantInput)(nil),     // 7: conferences.ConferenceParticipantInput
	(*UpdateAttendanceInput)(nil),          // 8: conferences.UpdateAttendanceInput
	(*generic.Pagination)(nil),             // 9: lms_conference_services.Pagination
	(*generic.Id)(nil),                     // 10: lms_conference_services.Id
	(*generic.BoolMessage)(nil),            // 11: lms_conference_services.BoolMessage
}
var file_conference_conferences_conference_message_proto_depIdxs = []int32{
	0,  // 0: conferences.ConferenceList.conferences:type_name -> conferences.Conference
	9,  // 1: conferences.ConferenceListInput.pagination:type_name -> lms_conference_services.Pagination
	4,  // 2: conferences.ConferenceParticipantList.participants:type_name -> conferences.ConferenceParticipant
	9,  // 3: conferences.ConferenceParticipantListInput.pagination:type_name -> lms_conference_services.Pagination
	2,  // 4: conferences.ConferenceService.List:input_type -> conferences.ConferenceListInput
	10, // 5: conferences.ConferenceService.Get:input_type -> lms_conference_services.Id
	3,  // 6: conferences.ConferenceService.Create:input_type -> conferences.ConferenceInput
	0,  // 7: conferences.ConferenceService.Update:input_type -> conferences.Conference
	10, // 8: conferences.ConferenceService.Delete:input_type -> lms_conference_services.Id
	6,  // 9: conferences.ConferenceParticipantService.List:input_type -> conferences.ConferenceParticipantListInput
	7,  // 10: conferences.ConferenceParticipantService.Create:input_type -> conferences.ConferenceParticipantInput
	8,  // 11: conferences.ConferenceParticipantService.UpdateAttendance:input_type -> conferences.UpdateAttendanceInput
	10, // 12: conferences.ConferenceParticipantService.Delete:input_type -> lms_conference_services.Id
	1,  // 13: conferences.ConferenceService.List:output_type -> conferences.ConferenceList
	0,  // 14: conferences.ConferenceService.Get:output_type -> conferences.Conference
	0,  // 15: conferences.ConferenceService.Create:output_type -> conferences.Conference
	0,  // 16: conferences.ConferenceService.Update:output_type -> conferences.Conference
	11, // 17: conferences.ConferenceService.Delete:output_type -> lms_conference_services.BoolMessage
	5,  // 18: conferences.ConferenceParticipantService.List:output_type -> conferences.ConferenceParticipantList
	4,  // 19: conferences.ConferenceParticipantService.Create:output_type -> conferences.ConferenceParticipant
	4,  // 20: conferences.ConferenceParticipantService.UpdateAttendance:output_type -> conferences.ConferenceParticipant
	11, // 21: conferences.ConferenceParticipantService.Delete:output_type -> lms_conference_services.BoolMessage
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_conference_conferences_conference_message_proto_init() }
func file_conference_conferences_conference_message_proto_init() {
	if File_conference_conferences_conference_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conference_conferences_conference_message_proto_rawDesc), len(file_conference_conferences_conference_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_conference_conferences_conference_message_proto_goTypes,
		DependencyIndexes: file_conference_conferences_conference_message_proto_depIdxs,
		MessageInfos:      file_conference_conferences_conference_message_proto_msgTypes,
	}.Build()
	File_conference_conferences_conference_message_proto = out.File
	file_conference_conferences_conference_message_proto_goTypes = nil
	file_conference_conferences_conference_message_proto_depIdxs = nil
}
