// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: conference/conferences/conference_message.proto

package conferences

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	generic "lms-gateway/pb/conference/generic"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConferenceService_List_FullMethodName   = "/conferences.ConferenceService/List"
	ConferenceService_Get_FullMethodName    = "/conferences.ConferenceService/Get"
	ConferenceService_Create_FullMethodName = "/conferences.ConferenceService/Create"
	ConferenceService_Update_FullMethodName = "/conferences.ConferenceService/Update"
	ConferenceService_Delete_FullMethodName = "/conferences.ConferenceService/Delete"
)

// ConferenceServiceClient is the client API for ConferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConferenceServiceClient interface {
	List(ctx context.Context, in *ConferenceListInput, opts ...grpc.CallOption) (*ConferenceList, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Conference, error)
	Create(ctx context.Context, in *ConferenceInput, opts ...grpc.CallOption) (*Conference, error)
	Update(ctx context.Context, in *Conference, opts ...grpc.CallOption) (*Conference, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type conferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConferenceServiceClient(cc grpc.ClientConnInterface) ConferenceServiceClient {
	return &conferenceServiceClient{cc}
}

func (c *conferenceServiceClient) List(ctx context.Context, in *ConferenceListInput, opts ...grpc.CallOption) (*ConferenceList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConferenceList)
	err := c.cc.Invoke(ctx, ConferenceService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, ConferenceService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceServiceClient) Create(ctx context.Context, in *ConferenceInput, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, ConferenceService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceServiceClient) Update(ctx context.Context, in *Conference, opts ...grpc.CallOption) (*Conference, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Conference)
	err := c.cc.Invoke(ctx, ConferenceService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, ConferenceService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConferenceServiceServer is the server API for ConferenceService service.
// All implementations should embed UnimplementedConferenceServiceServer
// for forward compatibility.
type ConferenceServiceServer interface {
	List(context.Context, *ConferenceListInput) (*ConferenceList, error)
	Get(context.Context, *generic.Id) (*Conference, error)
	Create(context.Context, *ConferenceInput) (*Conference, error)
	Update(context.Context, *Conference) (*Conference, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedConferenceServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConferenceServiceServer struct{}

func (UnimplementedConferenceServiceServer) List(context.Context, *ConferenceListInput) (*ConferenceList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConferenceServiceServer) Get(context.Context, *generic.Id) (*Conference, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedConferenceServiceServer) Create(context.Context, *ConferenceInput) (*Conference, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConferenceServiceServer) Update(context.Context, *Conference) (*Conference, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedConferenceServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConferenceServiceServer) testEmbeddedByValue() {}

// UnsafeConferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConferenceServiceServer will
// result in compilation errors.
type UnsafeConferenceServiceServer interface {
	mustEmbedUnimplementedConferenceServiceServer()
}

func RegisterConferenceServiceServer(s grpc.ServiceRegistrar, srv ConferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedConferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConferenceService_ServiceDesc, srv)
}

func _ConferenceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConferenceListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).List(ctx, req.(*ConferenceListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConferenceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).Create(ctx, req.(*ConferenceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Conference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).Update(ctx, req.(*Conference))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ConferenceService_ServiceDesc is the grpc.ServiceDesc for ConferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conferences.ConferenceService",
	HandlerType: (*ConferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ConferenceService_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ConferenceService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConferenceService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ConferenceService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConferenceService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conference/conferences/conference_message.proto",
}

const (
	ConferenceParticipantService_List_FullMethodName             = "/conferences.ConferenceParticipantService/List"
	ConferenceParticipantService_Create_FullMethodName           = "/conferences.ConferenceParticipantService/Create"
	ConferenceParticipantService_UpdateAttendance_FullMethodName = "/conferences.ConferenceParticipantService/UpdateAttendance"
	ConferenceParticipantService_Delete_FullMethodName           = "/conferences.ConferenceParticipantService/Delete"
)

// ConferenceParticipantServiceClient is the client API for ConferenceParticipantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConferenceParticipantServiceClient interface {
	List(ctx context.Context, in *ConferenceParticipantListInput, opts ...grpc.CallOption) (*ConferenceParticipantList, error)
	Create(ctx context.Context, in *ConferenceParticipantInput, opts ...grpc.CallOption) (*ConferenceParticipant, error)
	UpdateAttendance(ctx context.Context, in *UpdateAttendanceInput, opts ...grpc.CallOption) (*ConferenceParticipant, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
}

type conferenceParticipantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConferenceParticipantServiceClient(cc grpc.ClientConnInterface) ConferenceParticipantServiceClient {
	return &conferenceParticipantServiceClient{cc}
}

func (c *conferenceParticipantServiceClient) List(ctx context.Context, in *ConferenceParticipantListInput, opts ...grpc.CallOption) (*ConferenceParticipantList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConferenceParticipantList)
	err := c.cc.Invoke(ctx, ConferenceParticipantService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceParticipantServiceClient) Create(ctx context.Context, in *ConferenceParticipantInput, opts ...grpc.CallOption) (*ConferenceParticipant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConferenceParticipant)
	err := c.cc.Invoke(ctx, ConferenceParticipantService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceParticipantServiceClient) UpdateAttendance(ctx context.Context, in *UpdateAttendanceInput, opts ...grpc.CallOption) (*ConferenceParticipant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConferenceParticipant)
	err := c.cc.Invoke(ctx, ConferenceParticipantService_UpdateAttendance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conferenceParticipantServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, ConferenceParticipantService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConferenceParticipantServiceServer is the server API for ConferenceParticipantService service.
// All implementations should embed UnimplementedConferenceParticipantServiceServer
// for forward compatibility.
type ConferenceParticipantServiceServer interface {
	List(context.Context, *ConferenceParticipantListInput) (*ConferenceParticipantList, error)
	Create(context.Context, *ConferenceParticipantInput) (*ConferenceParticipant, error)
	UpdateAttendance(context.Context, *UpdateAttendanceInput) (*ConferenceParticipant, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
}

// UnimplementedConferenceParticipantServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConferenceParticipantServiceServer struct{}

func (UnimplementedConferenceParticipantServiceServer) List(context.Context, *ConferenceParticipantListInput) (*ConferenceParticipantList, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConferenceParticipantServiceServer) Create(context.Context, *ConferenceParticipantInput) (*ConferenceParticipant, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedConferenceParticipantServiceServer) UpdateAttendance(context.Context, *UpdateAttendanceInput) (*ConferenceParticipant, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAttendance not implemented")
}
func (UnimplementedConferenceParticipantServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedConferenceParticipantServiceServer) testEmbeddedByValue() {}

// UnsafeConferenceParticipantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConferenceParticipantServiceServer will
// result in compilation errors.
type UnsafeConferenceParticipantServiceServer interface {
	mustEmbedUnimplementedConferenceParticipantServiceServer()
}

func RegisterConferenceParticipantServiceServer(s grpc.ServiceRegistrar, srv ConferenceParticipantServiceServer) {
	// If the following call panics, it indicates UnimplementedConferenceParticipantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConferenceParticipantService_ServiceDesc, srv)
}

func _ConferenceParticipantService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConferenceParticipantListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceParticipantServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceParticipantService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceParticipantServiceServer).List(ctx, req.(*ConferenceParticipantListInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceParticipantService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConferenceParticipantInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceParticipantServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceParticipantService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceParticipantServiceServer).Create(ctx, req.(*ConferenceParticipantInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceParticipantService_UpdateAttendance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAttendanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceParticipantServiceServer).UpdateAttendance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceParticipantService_UpdateAttendance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceParticipantServiceServer).UpdateAttendance(ctx, req.(*UpdateAttendanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConferenceParticipantService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConferenceParticipantServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConferenceParticipantService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConferenceParticipantServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

// ConferenceParticipantService_ServiceDesc is the grpc.ServiceDesc for ConferenceParticipantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConferenceParticipantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conferences.ConferenceParticipantService",
	HandlerType: (*ConferenceParticipantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ConferenceParticipantService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _ConferenceParticipantService_Create_Handler,
		},
		{
			MethodName: "UpdateAttendance",
			Handler:    _ConferenceParticipantService_UpdateAttendance_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ConferenceParticipantService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conference/conferences/conference_message.proto",
}
